<script type="text/javascript">
    var mymo_cfg = {
        "act": "",
        "post_url": "{{ url()->current() }}",
        "ajax_url": "",
        "set_movie_view_url": "{{ route('watch.set_view', [$info->slug]) }}",
        "player_url": "{{ isset($player_id) ? route('watch.player', [$info->slug, $player_id]) : '' }}",
        "rating_url": "{{ route('watch.rating', [$info->slug]) }}",
        "loading_img": "{{ asset('styles/themes/mymo/images/ajax-loader.gif') }}",
        "eps_slug": "eps",
        "server_slug": "s",
        "type_slug": "slug-2",
        "post_title": "{{ $info->name }}",
        "post_id": '{{ isset($is_watch) ? $info->id : '' }}',
        "episode_slug": "",
        "server": 1,
        "player_error_detect": "display_modal",
        "paging_episode": "false",
        "episode_display": "show_list_eps",
        "episode_nav_num": 100,
        "auto_reset_cache": true,
        "resume_playback": true,
        "resume_text": "@lang('mymo::app.automatically_replay_the_movie')",
        "resume_text_2": "@lang('mymo::app.replay_from_begin')",
        "playback": "@lang('mymo::app.playback')",
        "continue_watching": "@lang('mymo::app.continue_watching')",
        "player_reload": "@lang('mymo::app.player_reload')",
        "jw_error_msg_0": "",
        "jw_error_msg_1": "@lang('mymo::app.video_error_can_not_be_played')",
        "jw_error_msg_2": "@lang('mymo::app.to_continue_watching_click_reload_player_button')",
        "jw_error_msg_3": "@lang('mymo::app.or_click_on_buttons_listed_below')",
        "light_on": "@lang('mymo::app.light_on')",
        "light_off": "@lang('mymo::app.light_off')",
        "expand": "@lang('mymo::app.expand')",
        "collapse": "@lang('mymo::app.collapse')",
        "player_loading": "@lang('mymo::app.player_loading')",
        "player_autonext": "@lang('mymo::app.player_autonext')",
        "is_adult": false,
        "adult_title": "@lang('mymo::app.adult_content_warning')",
        "adult_content": "",
        "show_only_once": "@lang('mymo::app.show_only_once')",
        "exit_btn": "@lang('mymo::app.exit')",
        "is_18plus": "",
        "report_lng": {
            "title": "{{ $info->name }}",
            "alert": "",
            "msg": "@lang('mymo::app.content')",
            "msg_success": "@lang('mymo::app.thank_you_for_submitting_error_message')",
            "loading_img": "{{ asset('styles/themes/mymo/images/loading.gif') }}",
            "report_btn": "@lang('mymo::app.report')",
            "name_or_email": "@lang('mymo::app.name')",
            "close": "@lang('mymo::app.close')"
        }
    }
</script>