import React from 'react';
import cx from 'classnames';
import { ColProps } from '.';

const defaultCol = {
  marginLeft: 4,
  marginRight: 4,
  paddingTop: 0,
  paddingBottom: 0,
  paddingVertical: 4,
  color: { r: 92, g: 90, b: 90, a: 1 },
};
export const JW_Col = (props: Partial<ColProps>) => {
  props = {
    ...defaultCol,
    ...(props as any),
  };
  const {
    children,
    col,
    color,
    style,
    mobile,
    tablet,
    className,
    marginLeft,
    marginRight,
    paddingTop,
    paddingBottom,
    paddingVertical,
  } = props;
  let colMobile = mobile;
  if (!mobile || mobile < 1 || mobile > 12) {
    colMobile = 12;
  }
  return (
    <div
      className={cx([
        className,
        {
          'ml-0': marginLeft === 0,
          'ml-1': marginLeft === 1,
          'ml-2': marginLeft === 2,
          'ml-3': marginLeft === 3,
          'ml-4': marginLeft === 4,
          'ml-5': marginLeft === 5,
          'ml-6': marginLeft === 6,
          'ml-8': marginLeft === 8,
          'ml-10': marginLeft === 10,
          'ml-12': marginLeft === 12,
          'ml-16': marginLeft === 16,
          'ml-20': marginLeft === 20,
          'ml-24': marginLeft === 24,
          'ml-32': marginLeft === 32,
          'ml-40': marginLeft === 40,
          'ml-48': marginLeft === 48,
          'ml-56': marginLeft === 56,
          'ml-64': marginLeft === 64,
          'ml-auto': marginLeft === 'auto',
        },
        {
          'mr-0': marginRight === 0,
          'mr-1': marginRight === 1,
          'mr-2': marginRight === 2,
          'mr-3': marginRight === 3,
          'mr-4': marginRight === 4,
          'mr-5': marginRight === 5,
          'mr-6': marginRight === 6,
          'mr-8': marginRight === 8,
          'mr-10': marginRight === 10,
          'mr-12': marginRight === 12,
          'mr-16': marginRight === 16,
          'mr-20': marginRight === 20,
          'mr-24': marginRight === 24,
          'mr-32': marginRight === 32,
          'mr-40': marginRight === 40,
          'mr-48': marginRight === 48,
          'mr-56': marginRight === 56,
          'mr-64': marginRight === 64,
          'mr-auto': marginRight === 'auto',
        },
        {
          'pt-0': paddingTop === 0,
          'pt-1': paddingTop === 1,
          'pt-2': paddingTop === 2,
          'pt-3': paddingTop === 3,
          'pt-4': paddingTop === 4,
          'pt-5': paddingTop === 5,
          'pt-6': paddingTop === 6,
          'pt-8': paddingTop === 8,
          'pt-10': paddingTop === 10,
          'pt-12': paddingTop === 12,
          'pt-16': paddingTop === 16,
          'pt-20': paddingTop === 20,
          'pt-24': paddingTop === 24,
          'pt-32': paddingTop === 32,
          'pt-40': paddingTop === 40,
          'pt-48': paddingTop === 48,
          'pt-56': paddingTop === 56,
          'pt-64': paddingTop === 64,
          'pt-auto': paddingTop === 'auto',
        },
        {
          'pb-0': paddingBottom === 0,
          'pb-1': paddingBottom === 1,
          'pb-2': paddingBottom === 2,
          'pb-3': paddingBottom === 3,
          'pb-4': paddingBottom === 4,
          'pb-5': paddingBottom === 5,
          'pb-6': paddingBottom === 6,
          'pb-8': paddingBottom === 8,
          'pb-10': paddingBottom === 10,
          'pb-12': paddingBottom === 12,
          'pb-16': paddingBottom === 16,
          'pb-20': paddingBottom === 20,
          'pb-24': paddingBottom === 24,
          'pb-32': paddingBottom === 32,
          'pb-40': paddingBottom === 40,
          'pb-48': paddingBottom === 48,
          'pb-56': paddingBottom === 56,
          'pb-64': paddingBottom === 64,
          'pb-auto': paddingBottom === 'auto',
        },
        {
          'px-0': paddingVertical === 0,
          'px-1': paddingVertical === 1,
          'px-2': paddingVertical === 2,
          'px-3': paddingVertical === 3,
          'px-4': paddingVertical === 4,
          'px-5': paddingVertical === 5,
          'px-6': paddingVertical === 6,
          'px-8': paddingVertical === 8,
          'px-10': paddingVertical === 10,
          'px-12': paddingVertical === 12,
          'px-16': paddingVertical === 16,
          'px-20': paddingVertical === 20,
          'px-24': paddingVertical === 24,
          'px-32': paddingVertical === 32,
          'px-40': paddingVertical === 40,
          'px-48': paddingVertical === 48,
          'px-56': paddingVertical === 56,
          'px-64': paddingVertical === 64,
          'px-auto': paddingVertical === 'auto',
        },
        {
          'col-span-1': colMobile === 1,
          'col-span-2': colMobile === 2,
          'col-span-3': colMobile === 3,
          'col-span-4': colMobile === 4,
          'col-span-5': colMobile === 5,
          'col-span-6': colMobile === 6,
          'col-span-7': colMobile === 7,
          'col-span-8': colMobile === 8,
          'col-span-9': colMobile === 9,
          'col-span-10': colMobile === 10,
          'col-span-11': colMobile === 11,
          'col-span-12': colMobile === 12,
        },
        {
          'sm:col-span-1': col && colMobile === 1,
          'sm:col-span-2': col && colMobile === 2,
          'sm:col-span-3': col && colMobile === 3,
          'sm:col-span-4': col && colMobile === 4,
          'sm:col-span-5': col && colMobile === 5,
          'sm:col-span-6': col && colMobile === 6,
          'sm:col-span-7': col && colMobile === 7,
          'sm:col-span-8': col && colMobile === 8,
          'sm:col-span-9': col && colMobile === 9,
          'sm:col-span-10': col && colMobile === 10,
          'sm:col-span-11': col && colMobile === 11,
          'sm:col-span-12': col && colMobile === 12,
        },
        {
          'md:col-span-1': tablet === 1,
          'md:col-span-2': tablet === 2,
          'md:col-span-3': tablet === 3,
          'md:col-span-4': tablet === 4,
          'md:col-span-5': tablet === 5,
          'md:col-span-6': tablet === 6,
          'md:col-span-7': tablet === 7,
          'md:col-span-8': tablet === 8,
          'md:col-span-9': tablet === 9,
          'md:col-span-10': tablet === 10,
          'md:col-span-11': tablet === 11,
          'md:col-span-12': tablet === 12,
        },
        {
          'md:col-span-1': !tablet && col === 1,
          'md:col-span-2': !tablet && col === 2,
          'md:col-span-3': !tablet && col === 3,
          'md:col-span-4': !tablet && col === 4,
          'md:col-span-5': !tablet && col === 5,
          'md:col-span-6': !tablet && col === 6,
          'md:col-span-7': !tablet && col === 7,
          'md:col-span-8': !tablet && col === 8,
          'md:col-span-9': !tablet && col === 9,
          'md:col-span-10': !tablet && col === 10,
          'md:col-span-11': !tablet && col === 11,
          'md:col-span-12': !tablet && col === 12,
        },
        {
          'lg:col-span-1': col === 1,
          'lg:col-span-2': col === 2,
          'lg:col-span-3': col === 3,
          'lg:col-span-4': col === 4,
          'lg:col-span-5': col === 5,
          'lg:col-span-6': col === 6,
          'lg:col-span-7': col === 7,
          'lg:col-span-8': col === 8,
          'lg:col-span-9': col === 9,
          'lg:col-span-10': col === 10,
          'lg:col-span-11': col === 11,
          'lg:col-span-12': col === 12,
        },
      ])}
      style={{
        ...style,
        ...{
          backgroundColor: `rgba(${Object.values(color as any)})`,
        },
      }}
    >
      {children}
    </div>
  );
};
