import React from 'react';
import cx from 'classnames';
import { IconProps } from './icon.type';

const defaultProps = {
  fontSize: 8,
  fontSizeOnlyTablet: 0,
  fontSizeOnlyMobile: 0,
  fontWeight: 5,
  fontWeightOnlyTablet: 0,
  fontWeightOnlyMobile: 0,
  // color: { r: 0, g: 0, b: 0, a: 1 },
  margin: [0, 0, 0, 0],
};

export const JW_Icon = (props: Partial<IconProps>) => {
  props = {
    ...defaultProps,
    ...props,
  };

  const {
    classIcon,
    fontSize,
    fontSizeOnlyTablet,
    fontSizeOnlyMobile,
    fontWeight,
    fontWeightOnlyTablet,
    fontWeightOnlyMobile,
    color,
    margin,
    style,
  } = props;

  return (
    <span
      className={cx([
        {
          'lg:text-xs': fontSize === 1,
          'lg:text-sm': fontSize === 2,
          'lg:text-base': fontSize === 3,
          'lg:text-lg': fontSize === 4,
          'lg:text-xl': fontSize === 5,
          'lg:text-2xl': fontSize === 6,
          'lg:text-3xl': fontSize === 7,
          'lg:text-4xl': fontSize === 8,
          'lg:text-5xl': fontSize === 9,
          'lg:text-6xl': fontSize >= 10,
        },
        {
          'text-xs': fontSizeOnlyMobile === 1,
          'text-sm': fontSizeOnlyMobile === 2,
          'text-base': fontSizeOnlyMobile === 3,
          'text-lg': fontSizeOnlyMobile === 4,
          'text-xl': fontSizeOnlyMobile === 5,
          'text-2xl': fontSizeOnlyMobile === 6,
          'text-3xl': fontSizeOnlyMobile === 7,
          'text-4xl': fontSizeOnlyMobile === 8,
          'text-5xl': fontSizeOnlyMobile === 9,
          'text-6xl': fontSizeOnlyMobile === 10,
        },
        {
          'text-xs': !fontSizeOnlyMobile && fontSize === 1,
          'text-sm': !fontSizeOnlyMobile && fontSize === 2,
          'text-base': !fontSizeOnlyMobile && fontSize === 3,
          'text-lg': !fontSizeOnlyMobile && fontSize === 4,
          'text-xl': !fontSizeOnlyMobile && fontSize === 5,
          'text-2xl': !fontSizeOnlyMobile && fontSize === 6,
          'text-3xl': !fontSizeOnlyMobile && fontSize === 7,
          'text-4xl': !fontSizeOnlyMobile && fontSize === 8,
          'text-5xl': !fontSizeOnlyMobile && fontSize === 9,
          'text-6xl': !fontSizeOnlyMobile && fontSize === 10,
        },
        {
          'sm:text-xs': fontSizeOnlyTablet === 1,
          'sm:text-sm': fontSizeOnlyTablet === 2,
          'sm:text-base': fontSizeOnlyTablet === 3,
          'sm:text-lg': fontSizeOnlyTablet === 4,
          'sm:text-xl': fontSizeOnlyTablet === 5,
          'sm:text-2xl': fontSizeOnlyTablet === 6,
          'sm:text-3xl': fontSizeOnlyTablet === 7,
          'sm:text-4xl': fontSizeOnlyTablet === 8,
          'sm:text-5xl': fontSizeOnlyTablet === 9,
          'sm:text-6xl': fontSizeOnlyTablet === 10,
        },
        {
          'sm:text-xs': !fontSizeOnlyTablet && fontSize === 1,
          'sm:text-sm': !fontSizeOnlyTablet && fontSize === 2,
          'sm:text-base': !fontSizeOnlyTablet && fontSize === 3,
          'sm:text-lg': !fontSizeOnlyTablet && fontSize === 4,
          'sm:text-xl': !fontSizeOnlyTablet && fontSize === 5,
          'sm:text-2xl': !fontSizeOnlyTablet && fontSize === 6,
          'sm:text-3xl': !fontSizeOnlyTablet && fontSize === 7,
          'sm:text-4xl': !fontSizeOnlyTablet && fontSize === 8,
          'sm:text-5xl': !fontSizeOnlyTablet && fontSize === 9,
          'sm:text-6xl': !fontSizeOnlyTablet && fontSize === 10,
        },
        {
          'lg:font-hairline': fontWeight === 1,
          'lg:font-thin': fontWeight === 2,
          'lg:font-light': fontWeight === 3,
          'lg:font-normal': fontWeight === 4,
          'lg:font-medium': fontWeight === 5,
          'lg:font-semibold': fontWeight === 6,
          'lg:font-bold': fontWeight === 7,
          'lg:font-extrabold': fontWeight === 8,
          'lg:font-black': fontWeight === 9,
        },
        {
          'font-hairline': fontWeightOnlyMobile === 1,
          'font-thin': fontWeightOnlyMobile === 2,
          'font-light': fontWeightOnlyMobile === 3,
          'font-normal': fontWeightOnlyMobile === 4,
          'font-medium': fontWeightOnlyMobile === 5,
          'font-semibold': fontWeightOnlyMobile === 6,
          'font-bold': fontWeightOnlyMobile === 7,
          'font-extrabold': fontWeightOnlyMobile === 8,
          'font-black': fontWeightOnlyMobile === 9,
        },
        {
          'font-hairline': !fontWeightOnlyMobile && fontWeight === 1,
          'font-thin': !fontWeightOnlyMobile && fontWeight === 2,
          'font-light': !fontWeightOnlyMobile && fontWeight === 3,
          'font-normal': !fontWeightOnlyMobile && fontWeight === 4,
          'font-medium': !fontWeightOnlyMobile && fontWeight === 5,
          'font-semibold': !fontWeightOnlyMobile && fontWeight === 6,
          'font-bold': !fontWeightOnlyMobile && fontWeight === 7,
          'font-extrabold': !fontWeightOnlyMobile && fontWeight === 8,
          'font-black': !fontWeightOnlyMobile && fontWeight === 9,
        },
        {
          'sm:font-hairline': fontWeightOnlyTablet === 1,
          'sm:font-thin': fontWeightOnlyTablet === 2,
          'sm:font-light': fontWeightOnlyTablet === 3,
          'sm:font-normal': fontWeightOnlyTablet === 4,
          'sm:font-medium': fontWeightOnlyTablet === 5,
          'sm:font-semibold': fontWeightOnlyTablet === 6,
          'sm:font-bold': fontWeightOnlyTablet === 7,
          'sm:font-extrabold': fontWeightOnlyTablet === 8,
          'sm:font-black': fontWeightOnlyTablet === 9,
        },
        {
          'sm:font-hairline': !fontWeightOnlyTablet && fontWeight === 1,
          'sm:font-thin': !fontWeightOnlyTablet && fontWeight === 2,
          'sm:font-light': !fontWeightOnlyTablet && fontWeight === 3,
          'sm:font-normal': !fontWeightOnlyTablet && fontWeight === 4,
          'sm:font-medium': !fontWeightOnlyTablet && fontWeight === 5,
          'sm:font-semibold': !fontWeightOnlyTablet && fontWeight === 6,
          'sm:font-bold': !fontWeightOnlyTablet && fontWeight === 7,
          'sm:font-extrabold': !fontWeightOnlyTablet && fontWeight === 8,
          'sm:font-black': !fontWeightOnlyTablet && fontWeight === 9,
        },
        {
          'mt-0': margin[0] === 0,
          'mt-1': margin[0] === 1,
          'mt-2': margin[0] === 2,
          'mt-3': margin[0] === 3,
          'mt-4': margin[0] === 4,
          'mt-5': margin[0] === 5,
          'mt-6': margin[0] === 6,
          'mt-8': margin[0] === 7,
          'mt-10': margin[0] === 8,
          'mt-12': margin[0] === 9,
          'mt-16': margin[0] === 10,
          'mt-20': margin[0] === 11,
          'mt-24': margin[0] === 12,
          'mt-32': margin[0] === 13,
          'mt-40': margin[0] === 14,
          'mt-48': margin[0] === 15,
          'mt-56': margin[0] === 16,
          'mt-64': margin[0] === 17,
          'mt-auto': margin[0] === 18,
        },
        {
          'mr-0': margin[1] === 0,
          'mr-1': margin[1] === 1,
          'mr-2': margin[1] === 2,
          'mr-3': margin[1] === 3,
          'mr-4': margin[1] === 4,
          'mr-5': margin[1] === 5,
          'mr-6': margin[1] === 6,
          'mr-8': margin[1] === 7,
          'mr-10': margin[1] === 8,
          'mr-12': margin[1] === 9,
          'mr-16': margin[1] === 10,
          'mr-20': margin[1] === 11,
          'mr-24': margin[1] === 12,
          'mr-32': margin[1] === 13,
          'mr-40': margin[1] === 14,
          'mr-48': margin[1] === 15,
          'mr-56': margin[1] === 16,
          'mr-64': margin[1] === 17,
          'mr-auto': margin[1] === 18,
        },
        {
          'mb-0': margin[2] === 0,
          'mb-1': margin[2] === 1,
          'mb-2': margin[2] === 2,
          'mb-3': margin[2] === 3,
          'mb-4': margin[2] === 4,
          'mb-5': margin[2] === 5,
          'mb-6': margin[2] === 6,
          'mb-8': margin[2] === 7,
          'mb-10': margin[2] === 8,
          'mb-12': margin[2] === 9,
          'mb-16': margin[2] === 10,
          'mb-20': margin[2] === 11,
          'mb-24': margin[2] === 12,
          'mb-32': margin[2] === 13,
          'mb-40': margin[2] === 14,
          'mb-48': margin[2] === 15,
          'mb-56': margin[2] === 16,
          'mb-64': margin[2] === 17,
          'mb-auto': margin[2] === 18,
        },
        {
          'ml-0': margin[3] === 0,
          'ml-1': margin[3] === 1,
          'ml-2': margin[3] === 2,
          'ml-3': margin[3] === 3,
          'ml-4': margin[3] === 4,
          'ml-5': margin[3] === 5,
          'ml-6': margin[3] === 6,
          'ml-8': margin[3] === 7,
          'ml-10': margin[3] === 8,
          'ml-12': margin[3] === 9,
          'ml-16': margin[3] === 10,
          'ml-20': margin[3] === 11,
          'ml-24': margin[3] === 12,
          'ml-32': margin[3] === 13,
          'ml-40': margin[3] === 14,
          'ml-48': margin[3] === 15,
          'ml-56': margin[3] === 16,
          'ml-64': margin[3] === 17,
          'ml-auto': margin[3] === 18,
        },
      ])}
    >
      <i
        className={classIcon}
        style={{
          ...style,
          color: `rgba(${color ? Object.values(color as any) : null})`,
        }}
      ></i>
    </span>
  );
};
