<?php

namespace Juzaweb\API\Http\Resources\Media;

use Illuminate\Http\Resources\Json\ResourceCollection;

class FolderCollection extends ResourceCollection
{
    public function toArray($request): array
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}
